version: 2
executorType: docker
containerInfo:
  - image: node:6.9.4
  - image: rethinkdb:2.3.5
stages:
  build:
    workDir: /home/ubuntu/action
    steps:
      - type: add-ssh-keys
        fingerprints:
          - "53:a8:37:35:c3:7e:54:f5:19:f6:8e:a1:e0:78:52:da"
      - type: checkout
      - type: cache-restore
        key: action-{{ checksum "yarn.lock" }}
      - type: shell
        name: Install dependencies
        command: |
          apt-get update && \
          apt-get -yq install build-essential g++ && \
          npm i -g yarn && \
          yarn
      - type: cache-save
        key: action-{{ checksum "yarn.lock" }}
        paths:
          - /home/ubuntu/action/node_modules
      - type: shell
        name: Database migration
        command: npm run db:migrate
      - type: shell
        name: NPM lint
        command: npm run lint
      - type: shell
        name: NPM run test
        command: npm test
      - type: shell
        name: Build server
        command: npm run build:server
      - type: shell
        name: Build client
        command: npm run build:client

      - type: artifacts-store
        path: /home/ubuntu/action/build
        destination: build
