version: 2
executorType: docker
containerInfo:
  - image: node:6.9.4
  - image: rethinkdb:2.3.5
stages:
  build:
    workDir: /home/ubuntu/action
    steps:
      - type: checkout
      - type: add-ssh-keys
      - type: shell
        name: Install dependencies
        command: |
          apt-get update && \
          apt-get -yq install build-essential g++ && \
          npm i -g yarn && \
          yarn
      - type: shell
        name: Database migration
        command: npm run db:migrate
      - type: shell
        name: NPM lint
        command: npm run lint
      - type: shell
        name: NPM run test
        command: npm test
      - type: shell
        name: Build server
        command: npm run build:server
      - type: shell
        name: Build client
        command: npm run build:client

      - type: artifacts-store
        path: /home/ubuntu/action/build
        destination: build
