version: 2
executorType: docker
containerInfo:
  - image: node:6.9.4
  - image: rethinkdb:2.3.5
stages:
  build:
    workDir: /home/ubuntu/action
    steps:
      - type: checkout
      - type: add-ssh-keys
      - type: shell
        name: Install Dependencies
        command: |
          apt-get update && \
          apt-get install build-essential g++ && \
          npm i -g yarn && \
          yarn
      - type: shell
        name: NPM Test
        command: npm test
