version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0
      - image: rethinkdb:2.3.6
      - image: redis:3.2.8
      - image: cypress/base:10
        environment:
          TERM: xterm
    environment:
      CODECOV_TOKEN: "ebdd735e-579a-4afd-85fc-f53907544c31"
      DEVOPS_REPO: "git@github.com:ParabolInc/action-devops.git"
      DEVOPS_WORKDIR: "~/action-devops"
      GITHUB_REMOTE_DEVELOPMENT: "dokku@action-dev-nyc1-01.parabol.co:web"
      GITHUB_REMOTE_PRODUCTION: "dokku@action-production.parabol.co:web"
      GITHUB_REMOTE_STAGING: "dokku@action-staging.parabol.co:web"
      PRODUCTION_BACKUP_VOLUME: "/mnt/volume-nyc1-01/action-production"
      SENTRY_ORG: "parabol"
      SENTRY_PROJECT: "action-production"
    working_directory: ~/action
    steps:
      - add_ssh_keys:
          fingerprints:
            - "53:a8:37:35:c3:7e:54:f5:19:f6:8e:a1:e0:78:52:da"
      - run:
          name: Slack setup
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              curl --ssl -X POST -H 'Content-type: application/json' --data '{"text":"Starting CI and Deployment..."}' $SLACK_PROD_URL
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              curl --ssl -X POST -H 'Content-type: application/json' --data '{"text":"Starting CI and Deployment..."}' $SLACK_STAGING_URL
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              curl --ssl -X POST -H 'Content-type: application/json' --data '{"text":"Starting CI and Deployment..."}' $SLACK_DEV_URL
            fi
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: |
            yarn --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
          - ~/.cache/yarn
      - run:
          name: DevOps checkout
          command: |
            ssh-agent $(
            ssh-add -D;
            ssh-add ~/.ssh/id_rsa_53a83735c37e54f519f68ea1e07852da;
            git clone $DEVOPS_REPO $DEVOPS_WORKDIR
            )
      - run:
          name: NPM run test
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
            echo "info: development server deploy, skipping"
            # else
            #            npm run test
            #            mkdir test-report ; mv test-report.xml test-report
            fi
      - run:
          name: Cypress Tests
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ] || [ "${CIRCLE_BRANCH}" == "staging" ]; then
              cp $DEVOPS_WORKDIR/environments/cypress ./packages/cypress/.env
              cp $DEVOPS_WORKDIR/environments/cypress ./packages/server/.env
              # cypress docker image has a bug, sideloading these mitigates it
              sudo apt-get update && sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
              curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
              sudo python get-pip.py
              sudo pip install rethinkdb==2.3.0
              rethinkdb-restore --force packages/cypress/fixtures/rdb_test.tar.gz
              yarn workspace parabol-server db:migrate-testing
              yarn workspace parabol-server build
              yarn workspace parabol-server postdeploy
              yarn workspace parabol-cypress test
            fi
      - deploy:
          name: Possible deployment build
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_PRODUCTION}"
              export DEPLOY_ENV="production"
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_STAGING}"
              export DEPLOY_ENV="staging"
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_DEVELOPMENT}"
              export DEPLOY_ENV="development"
            else
              export DEPLOY_ENV="local"
            fi
            if [ -n "${GITHUB_REMOTE}" ]; then
              cp $DEVOPS_WORKDIR/environments/$DEPLOY_ENV ./packages/server/.env
              cp $DEVOPS_WORKDIR/keys/.googlecloudkey.$DEPLOY_ENV.json ./packages/server/.googlecloudkey.json
              yarn workspace parabol-server build:deploy &&
              export ACTION_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
              git config --global user.name "Parabol CircleCI"
              git config --global user.email "admin+circleci@parabol.co"
              git add ./packages/server/.googlecloudkey.json build -f
              git add ./packages/server/graphql/queryMap.json build -f
              git add ./packages/client/__generated__ build -f
              git commit -m "build $ACTION_VERSION"
            fi
      - deploy:
          name: Possible (production backup) and deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_PRODUCTION}"
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_STAGING}"
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              export GITHUB_REMOTE="${GITHUB_REMOTE_DEVELOPMENT}"
            fi
            if [ -n "${GITHUB_REMOTE}" ]; then
              git remote add dokku $GITHUB_REMOTE
              export SSH_DESTINATION=$(echo $GITHUB_REMOTE | cut -f1 -d:)
              ssh -o StrictHostKeyChecking=no "${SSH_DESTINATION}" -T >/dev/null
            fi &&
            if [ "${GITHUB_REMOTE}" == "${GITHUB_REMOTE_PRODUCTION}" ]; then
              $DEVOPS_WORKDIR/dokku/rethinkdb-backup.sh \
                -s "${SSH_DESTINATION}" -d "${PRODUCTION_BACKUP_VOLUME}"
            fi &&
            if [ -n "${GITHUB_REMOTE}" ]; then
              git push -f dokku $CIRCLE_BRANCH:master
            fi
      - run:
          name: walrus.ai end-to-end tests
          command: |
            npm install -g @walrusai/cli
            walrus -a ${WALRUS_API_KEY} ./walrus
      - store_artifacts:
          path: ~/action/build
          destination: build
      - run:
          name: Upload sentry artifacts
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              curl -sL https://sentry.io/get-cli/ | bash
              export ACTION_VERSION=$(grep '"version":' package.json | cut -d\" -f4)
              sentry-cli releases new "$ACTION_VERSION"
              sentry-cli releases files "$ACTION_VERSION" upload-sourcemaps ~/action/build
              sentry-cli releases finalize "$ACTION_VERSION"
            fi
      - store_test_results:
          path: ~/action/test-report
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
