name: Typecheck

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Typecheck
      run: |
        yarn
        yarn build:relay
        yarn typecheck
        yarn lint
      env:
        CI: true
